Fix assertion error about missing serializer_class
AssertionError: 'CollectionVersionViewSet' should either include a
`serializer_class` attribute, or override the `get_serializer_class()`
method.

[noissue]