Add missing params to `rebuild_metadata` in `AnsibleRepositoryViewSet` (#1311)
fixes: #1322

Endpoint
`/api/automation-hub/pulp/api/v3/repositories/ansible/ansible/{repository_pk}/versions/0/rebuild_metadata/`
fails with `Server error 500`

`rebuild_metada` params are missing `number` and `repository_pk`

```
pulp_1   | pulp [None]: django.request:ERROR: Internal Server Error: /api/automation-hub/pulp/api/v3/repositories/ansible/ansible/78a1653e-e6c7-4d5a-96c4-2ddfaef720dd/versions/0/rebuild_metadata/
pulp_1   | Traceback (most recent call last):
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
pulp_1   |     response = get_response(request)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
pulp_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
pulp_1   |     return view_func(*args, **kwargs)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
pulp_1   |     return self.dispatch(request, *args, **kwargs)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
pulp_1   |     response = self.handle_exception(exc)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
pulp_1   |     self.raise_uncaught_exception(exc)
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
pulp_1   |     raise exc
pulp_1   |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
pulp_1   |     response = handler(request, *args, **kwargs)
pulp_1   | TypeError: rebuild_metadata() got an unexpected keyword argument 'repository_pk'
```
Error only occurs for `rebuilding_metadata` in
`AnsibleRepositoryVersionViewSet`, `AnsibleRepositoryViewSet` works fine